### ISSUE TITLE
The documentation is wrong

### ISSUE THREAD

**Issue by dev-cyprium** [bunsvr/docs#4]
I tried to run your example from the docs:
```ts
import { routes } from '@stricjs/app';
import { text, json } from '@stricjs/app/send';

// Define and export your routes
export default routes()
    .get('/', () => text('Welcome to Stric!'))
    .post('/json', ctx => ctx.json().then(json));
```

I got the error that `.json` is undefined in TS linter as well as the running code.

Please change your example to:
```ts
import { routes } from "@stricjs/app";
import { text, json } from "@stricjs/app/send";

// Define and export your routes
export default routes()
  .get("/", () => text("Welcome to Stric!"))
  .post("/json", async (ctx) => {
    const body = (await ctx.req.json()) as any;
    return json(body);
  });
```

To make it work

**Comment by dev-cyprium** [comment]
I'd love to contribute and make this fix, just want to make sure that it's wrong, please let me know if I can contribute to your project @aquapi

**Comment by aquapi** [comment]
@dev-cyprium the project was scrapped I'm working on something else at the moment

**Comment by aquapi** [comment]
@dev-cyprium check out https://www.npmjs.com/package/@bit-js/byte
